// yijing.js - 周易六十四卦评分系统（梅花易数起卦法）
// 上卦=姓氏笔画%8，下卦=名字笔画%8，动爻=总笔画%6

const TRIGRAM_MAP = { 0: "坤", 1: "乾", 2: "兑", 3: "离", 4: "震", 5: "巽", 6: "坎", 7: "艮" };
const TRIGRAM_WUXING = { 乾:"金", 兑:"金", 离:"火", 震:"木", 巽:"木", 坎:"水", 艮:"土", 坤:"土" };
const TRIGRAM_SYMBOL = { 乾:"\u2630", 兑:"\u2631", 离:"\u2632", 震:"\u2633", 巽:"\u2634", 坎:"\u2635", 艮:"\u2636", 坤:"\u2637" };

const HEXAGRAM_SYMBOLS = {
  1: "\u4dc0",
  2: "\u4dc1",
  3: "\u4dc2",
  4: "\u4dc3",
  5: "\u4dc4",
  6: "\u4dc5",
  7: "\u4dc6",
  8: "\u4dc7",
  9: "\u4dc8",
  10: "\u4dc9",
  11: "\u4dca",
  12: "\u4dcb",
  13: "\u4dcc",
  14: "\u4dcd",
  15: "\u4dce",
  16: "\u4dcf",
  17: "\u4dd0",
  18: "\u4dd1",
  19: "\u4dd2",
  20: "\u4dd3",
  21: "\u4dd4",
  22: "\u4dd5",
  23: "\u4dd6",
  24: "\u4dd7",
  25: "\u4dd8",
  26: "\u4dd9",
  27: "\u4dda",
  28: "\u4ddb",
  29: "\u4ddc",
  30: "\u4ddd",
  31: "\u4dde",
  32: "\u4ddf",
  33: "\u4de0",
  34: "\u4de1",
  35: "\u4de2",
  36: "\u4de3",
  37: "\u4de4",
  38: "\u4de5",
  39: "\u4de6",
  40: "\u4de7",
  41: "\u4de8",
  42: "\u4de9",
  43: "\u4dea",
  44: "\u4deb",
  45: "\u4dec",
  46: "\u4ded",
  47: "\u4dee",
  48: "\u4def",
  49: "\u4df0",
  50: "\u4df1",
  51: "\u4df2",
  52: "\u4df3",
  53: "\u4df4",
  54: "\u4df5",
  55: "\u4df6",
  56: "\u4df7",
  57: "\u4df8",
  58: "\u4df9",
  59: "\u4dfa",
  60: "\u4dfb",
  61: "\u4dfc",
  62: "\u4dfd",
  63: "\u4dfe",
  64: "\u4dff",
};

const HEXAGRAM_DATA = [
  {num:1,name:"乾",upper:"乾",lower:"乾",fortune:"大吉",judgement:"元亨利贞",image:"天行健，君子以自强不息",desc:"乾为天，刚健中正，自强不息。象征创始、成功、强健",career:"开创事业的好时机",wealth:"正财偏财俱旺",relation:"关系主动稳固"},
  {num:2,name:"坤",upper:"坤",lower:"坤",fortune:"大吉",judgement:"元亨，利牝马之贞",image:"地势坤，君子以厚德载物",desc:"坤为地，厚德载物，柔顺包容。象征承载、包容、滋养",career:"宜守成不宜开创",wealth:"财富稳步增长",relation:"包容和睦"},
  {num:3,name:"屯",upper:"坎",lower:"震",fortune:"中平",judgement:"元亨利贞，勿用有攸往",image:"云雷，屯。君子以经纶",desc:"万物始生，艰难险阻。象征初生、艰难",career:"起步艰难需坚持",wealth:"艰难积累",relation:"需耐心培养"},
  {num:4,name:"蒙",upper:"艮",lower:"坎",fortune:"中平",judgement:"亨，匪我求童蒙",image:"山下出泉，蒙。君子以果行育德",desc:"蒙昧初开，启蒙教育。象征启蒙、学习",career:"学习成长阶段",wealth:"教育投资",relation:"教学相长"},
  {num:5,name:"需",upper:"坎",lower:"乾",fortune:"中吉",judgement:"有孚，光亨，贞吉",image:"云上于天，需。君子以饮食宴乐",desc:"等待时机，诚信守正。象征等待、准备",career:"等待最佳时机",wealth:"静待财运",relation:"耐心经营"},
  {num:6,name:"讼",upper:"乾",lower:"坎",fortune:"凶",judgement:"有孚窒惕，中吉",image:"天水违行，讼。君子以作事谋始",desc:"争讼不息，宜退不宜进。象征争讼、冲突",career:"避免法律纠纷",wealth:"破财消灾",relation:"易起争执"},
  {num:7,name:"师",upper:"坤",lower:"坎",fortune:"中吉",judgement:"贞，丈人吉，无咎",image:"地中有水，师。君子以容民畜众",desc:"统军之道，严明纪律。象征统率、管理",career:"领导才能发挥",wealth:"团队协作生财",relation:"有领导力"},
  {num:8,name:"比",upper:"坎",lower:"坤",fortune:"大吉",judgement:"吉，原筮元永贞",image:"地上有水，比。先王以建万国",desc:"亲附和协，团结互助。象征合作、亲和",career:"团队合作愉快",wealth:"合作共赢",relation:"人际关系好"},
  {num:9,name:"小畜",upper:"巽",lower:"乾",fortune:"中吉",judgement:"亨，密云不雨",image:"风行天上，小畜。君子以懿文德",desc:"小有积蓄，蓄势待发。象征积累、准备",career:"积蓄力量，等待时机",wealth:"有积蓄",relation:"稳步发展"},
  {num:10,name:"履",upper:"乾",lower:"兑",fortune:"中吉",judgement:"履虎尾，不咥人，亨",image:"上天下泽，履。君子以辨上下定民志",desc:"履行礼仪，小心谨慎。象征实践、行动",career:"踏实做事，谨慎前行",wealth:"正财稳定",relation:"礼貌尊重"},
  {num:11,name:"泰",upper:"坤",lower:"乾",fortune:"大吉",judgement:"小往大来，吉亨",image:"天地交泰，后以财成天地之道",desc:"天地交泰，万物通达。象征顺利、和谐、繁荣",career:"事业通达，上下和谐",wealth:"财运亨通",relation:"关系融洽"},
  {num:12,name:"否",upper:"乾",lower:"坤",fortune:"凶",judgement:"否之匪人，不利君子贞",image:"天地不交，否。君子以俭德辟难",desc:"天地不交，闭塞不通。象征阻塞、不通",career:"不宜扩张，以守为主",wealth:"财运不通",relation:"关系受阻"},
  {num:13,name:"同人",upper:"乾",lower:"离",fortune:"大吉",judgement:"同人于野，亨",image:"天与火，同人。君子以类族辨物",desc:"团结大同，志同道合。象征协作、团结",career:"合作共事，得道多助",wealth:"合作生财",relation:"同心同德"},
  {num:14,name:"大有",upper:"离",lower:"乾",fortune:"大吉",judgement:"元亨",image:"火在天上，大有。君子以遏恶扬善",desc:"大获丰收，富足有余。象征丰收、成就",career:"事业收获期",wealth:"财运旺盛",relation:"关系富足"},
  {num:15,name:"谦",upper:"坤",lower:"艮",fortune:"大吉",judgement:"亨，君子有终",image:"地中有山，谦。君子以裒多益寡",desc:"谦恭礼让，德行高尚。象征谦虚、稳重",career:"谦虚受益，得贵人相助",wealth:"稳步积累",relation:"谦和得体"},
  {num:16,name:"豫",upper:"震",lower:"坤",fortune:"中吉",judgement:"利建侯行师",image:"雷出地奋，豫。先王以作乐崇德",desc:"安乐愉悦，顺势而为。象征愉悦、安乐",career:"顺势而为，快乐工作",wealth:"偏财机遇",relation:"关系愉悦"},
  {num:17,name:"随",upper:"兑",lower:"震",fortune:"中吉",judgement:"元亨利贞，无咎",image:"泽中有雷，随。君子以向晦入宴息",desc:"随顺时势，灵活变通。象征跟随、顺应",career:"顺应时势，随遇而安",wealth:"随缘得财",relation:"随缘而安"},
  {num:18,name:"蛊",upper:"艮",lower:"巽",fortune:"凶",judgement:"元亨，利涉大川",image:"山下有风，蛊。君子以振民育德",desc:"整治腐败，拨乱反正。象征腐败、整治",career:"改革需要勇气",wealth:"先破后立",relation:"需治理"},
  {num:19,name:"临",upper:"坤",lower:"兑",fortune:"中吉",judgement:"元亨利贞",image:"泽上有地，临。君子以教思无穷",desc:"居高临下，督导管理。象征监督、引导",career:"领导管理之位",wealth:"管理之财",relation:"关心他人"},
  {num:20,name:"观",upper:"巽",lower:"坤",fortune:"中吉",judgement:"盥而不荐，有孚颙若",image:"风行地上，观。先王以省方观民设教",desc:"观察事理，审时度势。象征观察、洞察",career:"观察分析，找准方向",wealth:"审慎投资",relation:"善于观察"},
  {num:21,name:"噬嗑",upper:"离",lower:"震",fortune:"中平",judgement:"亨，利用狱",image:"雷电噬嗑，先王以明罚敕法",desc:"排除障碍，咬合沟通。象征审判、排除",career:"克服障碍",wealth:"诉讼之财",relation:"需坦诚沟通"},
  {num:22,name:"贲",upper:"艮",lower:"离",fortune:"中吉",judgement:"亨，小利有攸往",image:"山下有火，贲。君子以明庶政",desc:"文饰美化，文明礼仪。象征文采、修饰",career:"注重形象和包装",wealth:"文化之财",relation:"浪漫有情调"},
  {num:23,name:"剥",upper:"艮",lower:"坤",fortune:"凶",judgement:"不利有攸往",image:"山附于地，剥。上以厚下安宅",desc:"剥落衰败，小人当道。象征剥落、衰败",career:"不宜妄动",wealth:"防止破财",relation:"关系淡漠"},
  {num:24,name:"复",upper:"坤",lower:"震",fortune:"中吉",judgement:"亨，出入无疾",image:"雷在地中，复。先王以至日闭关",desc:"一阳来复，万物复苏。象征复兴、回归",career:"新的开始，复苏上升",wealth:"财运回升",relation:"重新开始"},
  {num:25,name:"无妄",upper:"乾",lower:"震",fortune:"中平",judgement:"元亨利贞",image:"天下雷行，无妄。先王以茂对时",desc:"不妄为，顺其自然。象征真实、自然",career:"顺其自然",wealth:"意外之财需谨慎",relation:"真诚相处"},
  {num:26,name:"大畜",upper:"艮",lower:"乾",fortune:"中吉",judgement:"利贞，不家食吉",image:"天在山中，大畜。君子以多识前言往行",desc:"积蓄力量，厚积薄发。象征积累、储备",career:"积累实力，等待爆发",wealth:"积蓄丰厚",relation:"积累感情"},
  {num:27,name:"颐",upper:"艮",lower:"震",fortune:"中吉",judgement:"贞吉，观颐",image:"山下有雷，颐。君子以慎言语节饮食",desc:"颐养身心，养精蓄锐。象征休养、滋养",career:"修养生息",wealth:"守成之财",relation:"相互滋养"},
  {num:28,name:"大过",upper:"兑",lower:"巽",fortune:"凶",judgement:"栋桡，利有攸往",image:"泽灭木，大过。君子以独立不惧",desc:"过度强大，物极必反。象征过度、极端",career:"不宜过度扩张",wealth:"大进大出",relation:"关系失衡"},
  {num:29,name:"坎",upper:"坎",lower:"坎",fortune:"凶",judgement:"习坎，有孚维心亨",image:"水洊至，习坎。君子以常德行",desc:"险陷重重，危机四伏。象征危险、陷阱",career:"困难期需谨慎",wealth:"不宜投资",relation:"易有波折"},
  {num:30,name:"离",upper:"离",lower:"离",fortune:"中吉",judgement:"利贞，亨",image:"明两作，离。大人以继明照于四方",desc:"光明照耀，文明连续。象征光明、智慧",career:"事业光明，智慧引领",wealth:"知识生财",relation:"热情明朗"},
  {num:31,name:"咸",upper:"兑",lower:"艮",fortune:"中吉",judgement:"亨，利贞",image:"山上有泽，咸。君子以虚受人",desc:"感应相通，男女之情。象征感应、交流",career:"人际沟通顺畅",wealth:"人脉生财",relation:"感情和谐"},
  {num:32,name:"恒",upper:"震",lower:"巽",fortune:"大吉",judgement:"亨，无咎，利贞",image:"雷风恒，君子以立不易方",desc:"持之以恒，恒久之道。象征坚持、稳定",career:"持之以恒必有成",wealth:"持续稳定的收入",relation:"感情长久稳固"},
  {num:33,name:"遁",upper:"乾",lower:"艮",fortune:"中吉",judgement:"亨，小利贞",image:"天下有山，遁。君子以远小人",desc:"急流勇退，适时退隐。象征退避、隐忍",career:"适时退让，保存实力",wealth:"保守理财",relation:"给彼此空间"},
  {num:34,name:"大壮",upper:"震",lower:"乾",fortune:"中吉",judgement:"利贞",image:"雷在天上，大壮。君子以非礼弗履",desc:"强盛壮大，正直发展。象征强大、力量",career:"实力强大，正当发展",wealth:"实力生财",relation:"强势需柔"},
  {num:35,name:"晋",upper:"离",lower:"坤",fortune:"大吉",judgement:"康侯用锡马蕃庶",image:"明出地上，晋。君子以自昭明德",desc:"步步高升，如日之升。象征晋升、进步",career:"事业上升期",wealth:"收入增加",relation:"共同进步"},
  {num:36,name:"明夷",upper:"坤",lower:"离",fortune:"中平",judgement:"利艰贞",image:"明入地中，明夷。君子以莅众",desc:"光明受损，韬光养晦。象征隐忍、等待",career:"暂避锋芒",wealth:"不宜投资",relation:"暂时隐忍"},
  {num:37,name:"家人",upper:"巽",lower:"离",fortune:"中吉",judgement:"利女贞",image:"风自火出，家人。君子以言有物而行有恒",desc:"家庭和睦，家道兴旺。象征家庭、亲情",career:"适合家族事业",wealth:"家庭理财",relation:"家庭美满"},
  {num:38,name:"睽",upper:"离",lower:"兑",fortune:"中平",judgement:"小事吉",image:"上火下泽，睽。君子以同而异",desc:"乖离分歧，求同存异。象征分歧、矛盾",career:"需协调分歧",wealth:"小心合伙",relation:"有分歧需沟通"},
  {num:39,name:"蹇",upper:"坎",lower:"艮",fortune:"中平",judgement:"利西南，不利东北",image:"山上有水，蹇。君子以反身修德",desc:"艰难险阻，知难而进。象征困难、险阻",career:"困难重重需耐心",wealth:"谨慎理财",relation:"需共同面对"},
  {num:40,name:"解",upper:"震",lower:"坎",fortune:"中吉",judgement:"利西南",image:"雷雨作，解。君子以赦过宥罪",desc:"解除困境，化解危机。象征解脱、化解",career:"困境即将解除",wealth:"财务改善",relation:"关系缓和"},
  {num:41,name:"损",upper:"艮",lower:"兑",fortune:"中平",judgement:"有孚，元吉",image:"山下有泽，损。君子以惩忿窒欲",desc:"减损自身，损失奉献。象征损失、减损",career:"暂时损失",wealth:"破财免灾",relation:"需要付出"},
  {num:42,name:"益",upper:"巽",lower:"震",fortune:"大吉",judgement:"利有攸往，利涉大川",image:"风雷，益。君子以见善则迁",desc:"增益发展，利人利己。象征增长、帮助",career:"快速发展期",wealth:"财运增加",relation:"互相增益"},
  {num:43,name:"夬",upper:"兑",lower:"乾",fortune:"中平",judgement:"扬于王庭",image:"泽上于天，夬。君子以施禄及下",desc:"决断果断，当断则断。象征决断、果断",career:"果断决策",wealth:"快速获利",relation:"速战速决"},
  {num:44,name:"姤",upper:"乾",lower:"巽",fortune:"中平",judgement:"女壮，勿用取女",image:"天下有风，姤。后以施命诰四方",desc:"相遇邂逅，机缘巧合。象征相遇、机缘",career:"有机遇也有风险",wealth:"意外之财",relation:"邂逅有缘"},
  {num:45,name:"萃",upper:"兑",lower:"坤",fortune:"大吉",judgement:"亨，王假有庙",image:"泽上于地，萃。君子以除戎器",desc:"人才汇聚，精英聚集。象征汇聚、精英",career:"人才聚集好发展",wealth:"众人拾柴",relation:"人缘极佳"},
  {num:46,name:"升",upper:"坤",lower:"巽",fortune:"大吉",judgement:"元亨，用见大人",image:"地中生木，升。君子以顺德",desc:"步步高升，持续上升。象征上升、进步",career:"事业发展上升",wealth:"收入提高",relation:"共同成长"},
  {num:47,name:"困",upper:"兑",lower:"坎",fortune:"凶",judgement:"亨，贞大人吉",image:"泽无水，困。君子以致命遂志",desc:"困境重重，坚守正道。象征困顿、困境",career:"耐心等待转机",wealth:"财务困难",relation:"关系困顿"},
  {num:48,name:"井",upper:"坎",lower:"巽",fortune:"中吉",judgement:"改邑不改井",image:"木上有水，井。君子以劳民劝相",desc:"滋养万物，源源不断。象征滋养、稳定",career:"稳定发展",wealth:"稳定收入",relation:"日久生情"},
  {num:49,name:"革",upper:"兑",lower:"离",fortune:"中吉",judgement:"己日乃孚，元亨利贞",image:"泽中有火，革。君子以治历明时",desc:"改革创新，破旧立新。象征变革、革新",career:"改革带来机遇",wealth:"创新得财",relation:"需要改变"},
  {num:50,name:"鼎",upper:"离",lower:"巽",fortune:"大吉",judgement:"元吉，亨",image:"木上有火，鼎。君子以正位凝命",desc:"鼎立天下，稳定成就。象征稳固、权威",career:"地位稳固",wealth:"财运稳固",relation:"关系稳定"},
  {num:51,name:"震",upper:"震",lower:"震",fortune:"中平",judgement:"亨，震来虩虩",image:"洊雷，震。君子以恐惧修省",desc:"震惊百里，临危不乱。象征震动、惊雷",career:"突发变动需冷静",wealth:"防突发破财",relation:"关系波动"},
  {num:52,name:"艮",upper:"艮",lower:"艮",fortune:"中吉",judgement:"艮其背，不获其身",image:"兼山，艮。君子以思不出其位",desc:"沉稳厚重，知止有度。象征停止、稳定",career:"稳扎稳打",wealth:"守成",relation:"稳重踏实"},
  {num:53,name:"渐",upper:"巽",lower:"艮",fortune:"大吉",judgement:"女归吉，利贞",image:"山上有木，渐。君子以居贤德善俗",desc:"循序渐进，步步高升。象征渐进、积累",career:"循序渐进必有所成",wealth:"逐步增长",relation:"稳步发展"},
  {num:54,name:"归妹",upper:"震",lower:"兑",fortune:"中平",judgement:"征凶，无攸利",image:"泽上有雷，归妹。君子以永终知敝",desc:"结合匹配，姻缘之象。象征结合、婚嫁",career:"合作需谨慎",wealth:"注意合伙",relation:"婚姻需用心"},
  {num:55,name:"丰",upper:"震",lower:"离",fortune:"大吉",judgement:"亨，王假之",image:"雷电皆至，丰。君子以折狱致刑",desc:"丰盛圆满，盛大繁荣。象征丰盛、繁荣",career:"事业繁荣",wealth:"财运旺盛",relation:"生活美满"},
  {num:56,name:"旅",upper:"离",lower:"艮",fortune:"中平",judgement:"小亨，旅贞吉",image:"山上有火，旅。君子以明慎用刑",desc:"旅居在外，漂泊不定。象征旅行、漂泊",career:"宜外出发展",wealth:"外地求财",relation:"异地缘分"},
  {num:57,name:"巽",upper:"巽",lower:"巽",fortune:"中吉",judgement:"小亨，利有攸往",image:"随风，巽。君子以申命行事",desc:"谦逊柔和，顺势而行。象征谦逊、顺从",career:"谦虚行事",wealth:"因势得财",relation:"温柔体贴"},
  {num:58,name:"兑",upper:"兑",lower:"兑",fortune:"大吉",judgement:"亨，利贞",image:"丽泽，兑。君子以朋友讲习",desc:"喜悦快乐，沟通顺畅。象征喜悦、沟通",career:"沟通顺畅",wealth:"口才生财",relation:"关系愉悦"},
  {num:59,name:"涣",upper:"巽",lower:"坎",fortune:"中吉",judgement:"亨，王假有庙",image:"风行水上，涣。先王以享于帝立庙",desc:"涣散聚合，聚散有时。象征离散、重组",career:"旧结束新开始",wealth:"调整投资",relation:"聚散有缘"},
  {num:60,name:"节",upper:"坎",lower:"兑",fortune:"中吉",judgement:"亨，苦节不可贞",image:"泽上有水，节。君子以制数度",desc:"节制适度，有度有节。象征节制、适度",career:"适度发展不宜过",wealth:"节制消费",relation:"有度相处"},
  {num:61,name:"中孚",upper:"巽",lower:"兑",fortune:"大吉",judgement:"豚鱼吉，利涉大川",image:"泽上有风，中孚。君子以议狱缓死",desc:"诚信感化，中正守信。象征诚信、信任",career:"以诚待人，事业顺利",wealth:"诚信生财",relation:"互信互爱"},
  {num:62,name:"小过",upper:"震",lower:"艮",fortune:"中平",judgement:"亨，利贞",image:"山上有雷，小过。君子以行过乎恭",desc:"小有过失，谨慎小心。象征小的过失",career:"宜谨慎行事",wealth:"宜保守",relation:"注意言行"},
  {num:63,name:"既济",upper:"坎",lower:"离",fortune:"大吉",judgement:"亨小，利贞",image:"水在火上，既济。君子以思患而豫防之",desc:"功德圆满，成功在望。象征完成、成就",career:"事业有成",wealth:"财富丰盈",relation:"关系和谐"},
  {num:64,name:"未济",upper:"离",lower:"坎",fortune:"中平",judgement:"亨，小狐汔济",image:"火在水上，未济。君子以慎辨物居方",desc:"尚未完成，继续努力。象征未完成、继续",career:"还需继续努力",wealth:"未完待续",relation:"继续培养"},
];

const FORTUNE_SCORE = { 大吉:100, 中吉:85, 中平:75, 凶:55, 大凶:30 };

function calculateGua(surnameStrokes, givenStrokes, totalStrokes) {
  const upperIdx = surnameStrokes % 8;
  const lowerIdx = givenStrokes % 8;
  const movingYao = (totalStrokes % 6) || 6;
  const upperGua = TRIGRAM_MAP[upperIdx];
  const lowerGua = TRIGRAM_MAP[lowerIdx];
  if (!upperGua || !lowerGua) return { hexagram: null, score: 60, fortune: "中平", desc: "无法确定卦象" };
  const h = HEXAGRAM_DATA.find(x => x.upper === upperGua && x.lower === lowerGua);
  if (!h) return { hexagram: null, score: 60, fortune: "中平", desc: "无法确定卦象" };
  return {
    hexagram: h.name + "卦",
    symbol: HEXAGRAM_SYMBOLS[h.num],
    number: h.num, name: h.name, fortune: h.fortune,
    judgement: h.judgement, image: h.image, desc: h.desc,
    career: h.career, wealth: h.wealth, relation: h.relation,
    score: FORTUNE_SCORE[h.fortune] || 60,
    upperGua: upperGua, lowerGua: lowerGua, movingYao: movingYao,
    upperWuxing: TRIGRAM_WUXING[upperGua], lowerWuxing: TRIGRAM_WUXING[lowerGua],
    upperSymbol: TRIGRAM_SYMBOL[upperGua], lowerSymbol: TRIGRAM_SYMBOL[lowerGua]
  };
}

export { HEXAGRAM_DATA, calculateGua, TRIGRAM_MAP, TRIGRAM_WUXING, FORTUNE_SCORE };